export const SEARCHED_USERS = 'SEARCHED_USERS';
export const RECEIVED_USERS = 'RECEIVED_USERS';
export const CLEARED_SEARCH_RESULTS = 'CLEARED_SEARCH_RESULTS';

export const REQUESTED_USER_REPOS = 'REQUESTED_USER_REPOS';
export const RECEIVED_USER_REPOS = 'RECEIVED_USER_REPOS';

export const CHECKED_ADMIN_ACCESS = 'CHECKED_ADMIN_ACCESS';
export const ACCESS_DENIED = 'ACCESS_DENIED';

export const LOGIN_COMPLETE = 'LOGIN_COMPLETE';
export const LOGIN_IN_PROGRESS = 'LOGIN_IN_PROGRESS';
export const LOGGED_OUT = 'LOGGED_OUT';
export const LOGOUT_IN_PROGRESS = 'LOGOUT_IN_PROGRESS';
export const TOKEN_REFRESHED = 'TOKEN_REFRESHED';
export const INITIALIZE = 'INITIALIZE';
